# application-app-prod.properties
# Production environment — no Swagger

# Eureka 
eureka.client.service-url.defaultZone=http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOST}:8761/eureka/
eureka.instance.hostname=${HOSTNAME}

# Datasource 
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

# Keycloak 
keycloak.issuer-uri=https://${KEYCLOAK_HOST}/realms/travel-agency

#  Swagger (DISABLED in prod) 
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

# Logging 
logging.level.root=WARN
logging.level.com.travelagency=INFO
spring.jpa.show-sql=false

# Security 
server.ssl.enabled=true
server.ssl.key-store=${SSL_KEYSTORE_PATH}
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12

# Actuator (restricted in prod) 
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

#  Audit 
audit.service.enabled=true
audit.service.url=http://${AUDIT_SERVICE_HOST}/api/audit
