# application-app-test.properties

# Datasource URL 
spring.datasource.url=jdbc:mysql://localhost:3306/producttestdb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Logging
logging.level.root=INFO
logging.level.com.travelagency=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Audit
audit.service.enabled=false

# Vault
spring.cloud.vault.kv.default-context=travel-agency/test/db
