# application-app-qa.properties

# Eureka 
eureka.client.service-url.defaultZone=http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOST}:8761/eureka/
eureka.instance.hostname=${HOSTNAME}

# Datasource 
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Keycloak 
keycloak.issuer-uri=http://${KEYCLOAK_HOST}/realms/travel-agency

# Swagger (on for QA testers) 
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Logging 
logging.level.root=INFO
logging.level.com.travelagency=DEBUG
spring.jpa.show-sql=true

# Actuator (broader in QA) 
management.endpoints.web.exposure.include=health,info,metrics,env,loggers
management.endpoint.health.show-details=always

# Audit 
audit.service.enabled=true
audit.service.url=http://${AUDIT_SERVICE_HOST}/api/audit
